export const FETCH_PROPOSALS_SUCCESS = "FETCH_PROPOSALS_SUCCESS";
export const FETCH_PROPOSALS_REQUEST = "FETCH_PROPOSALS_REQUEST";
export const FETCH_PROPOSALS_FAILURE = "FETCH_PROPOSALS_FAILURE";

export const FETCH_PROPOSAL_REQUEST = "FETCH_PROPOSAL_REQUEST";
export const FETCH_PROPOSAL_SUCCESS = "FETCH_PROPOSAL_SUCCESS";
export const FETCH_PROPOSAL_FAILURE = "FETCH_PROPOSAL_FAILURE";
